/* ============================================
   MR TYPE - words.js
   Word pools, quotes, sounds, ranks
   ============================================ */

const WORD_POOLS = {
  en: [
    "the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you",
    "do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my",
    "one","all","would","there","their","what","so","up","out","if","about","who","get","which",
    "go","me","when","make","can","like","time","no","just","him","know","take","people","into",
    "year","your","good","some","could","them","see","other","than","then","now","look","only",
    "come","its","over","think","also","back","after","use","two","how","our","work","first",
    "well","way","even","new","want","because","any","these","give","day","most","us","great",
    "between","need","large","often","hand","high","place","hold","turn","help","each","link",
    "load","save","read","write","build","code","data","file","game","input","java","keep","make",
    "node","open","post","query","run","set","type","user","view","access","call","drive","edit",
    "find","next","output","print","update","validate","wait","create","delete","import","export",
    "return","function","variable","string","number","boolean","array","object","class","module",
    "server","client","request","response","database","error","debug","test","deploy","version",
    "branch","commit","merge","push","pull","clone","fork","issue","release","feature","bug",
    "fix","patch","update","upgrade","install","remove","config","setting","option","default",
    "custom","public","private","static","dynamic","render","style","color","font","size","width",
    "height","margin","padding","border","display","flex","grid","block","inline","position",
    "event","click","hover","focus","blur","submit","reset","change","input","output","result",
    "value","key","index","count","length","sort","filter","map","reduce","find","include","push",
    "pop","shift","unshift","splice","slice","join","split","trim","replace","match","search",
    "start","end","begin","finish","complete","process","handle","manage","control","access",
    "load","store","cache","fetch","send","receive","connect","disconnect","open","close","read",
    "write","parse","format","encode","decode","encrypt","decrypt","hash","sign","verify","token",
    "session","cookie","header","body","param","query","route","path","url","api","rest","http",
    "web","app","mobile","desktop","cloud","local","remote","host","port","socket","stream","pipe",
    "async","await","promise","callback","event","emit","listen","subscribe","publish","observe",
    "login","logout","register","authenticate","authorize","permission","role","admin","user",
    "name","email","password","profile","avatar","setting","notification","message","alert",
    "confirm","cancel","back","next","previous","page","list","table","form","input","button",
    "link","image","video","audio","icon","text","label","title","heading","paragraph","section",
    "container","wrapper","layout","template","component","widget","plugin","extension","library",
    "framework","package","module","dependency","import","export","build","compile","run","test",
    "lint","format","deploy","publish","release","version","changelog","readme","license","docs",
    "comment","todo","fixme","hack","note","debug","log","warn","error","info","trace","assert",
    "equal","strict","deep","shallow","mock","stub","spy","fake","dummy","null","undefined",
    "true","false","zero","one","two","three","four","five","six","seven","eight","nine","ten",
    "small","large","big","tiny","huge","fast","slow","quick","easy","hard","simple","complex",
    "clean","dirty","fresh","old","new","modern","classic","basic","advanced","simple","detailed"
  ],
  uz: [
    "va","bu","bir","ham","uchun","bilan","lekin","agar","keyin","hali","endi","faqat","ham",
    "u","men","sen","biz","ular","siz","nima","qaysi","qanday","qachon","qayerda","kim","necha",
    "ko'p","oz","katta","kichik","yangi","eski","yaxshi","yomon","tez","sekin","ko'p","kam",
    "ishlamoq","kod","ma'lumot","fayl","o'yin","yordam","kiritish","saqlamoq","yuklamoq",
    "qilmoq","tugun","ochmoq","so'rov","o'qimoq","tur","foydalanuvchi","ko'rish","yozmoq",
    "kirish","orqaga","disk","tahrirlamoq","topmoq","olmoq","ushlamoq","qo'shmoq","bilmoq",
    "havola","harakat","keyingi","chiqish","ishga","o'rnatmoq","vaqt","yangilamoq","tekshirmoq",
    "kutmoq","yaratmoq","o'chirmoq","import","eksport","qaytarmoq","funksiya","o'zgaruvchi",
    "satr","son","mantiqiy","massiv","ob'ekt","sinf","modul","server","mijoz","so'rov",
    "javob","ma'lumotlar","xato","disk","sinov","joylashtirmoq","versiya","tarmoq","topshiriq",
    "birlashtirmoq","yuklash","klonlamoq","fork","muammo","chiqarish","xususiyat","qo'shimcha",
    "tuzatmoq","yamoq","yangilash","yaxshilash","o'rnatish","olib","sozlama","parametr","tanlov",
    "standart","maxsus","ommaviy","shaxsiy","statik","dinamik","ko'rsatmoq","uslub","rang",
    "shrift","hajm","kenglik","balandlik","chegara","ko'rinish","blok","chiziqli","holat",
    "voqea","bosish","sichqoncha","diqqat","yuborish","o'zgartirish","qiymat","kalit","indeks",
    "soni","uzunlik","saralash","filtrlash","xaritalash","qisqartirish","topmoq","qo'shmoq",
    "ajratmoq","kesish","birlashtirmoq","ajratmoq","qisqartirmoq","almashtirmoq","moslashtirmoq",
    "boshlash","tugatmoq","bajarmoq","boshqarmoq","nazorat","ruxsat","yuklash","saqlash",
    "kesh","olish","yuborish","qabul","ulanish","uzilish","ochmoq","yopmoq","o'qimoq",
    "yozmoq","tahlil","formatlash","kodlash","dekodlash","shifrlash","hal","imzolash",
    "tokenkirish","sessiya","kukilar","sarlavha","tana","parametr","yo'nalish","manzil",
    "web","dastur","mobil","ish","bulut","mahalliy","uzoq","server","port","soket","oqim",
    "sinxron","asinxron","va'da","qaytaruv","voqea","chiqarmoq","tinglash","obuna","nashr",
    "kirish","chiqish","ro'yxatdan","autentifikatsiya","ruxsat","admin","foydalanuvchi",
    "ism","elektron","parol","profil","sozlama","xabar","tasdiqlash","bekor","orqaga",
    "sahifa","ro'yxat","jadval","shakl","tugma","havola","rasm","video","audio","belgi",
    "matn","sarlavha","bo'lim","konteyner","shablonlar","komponent","plagin","kutubxona",
    "to'plam","modul","bog'liqlik","qurish","kompilyatsiya","ishga","sinov","nashr","hujjat"
  ],
  ru: [
    "и","в","не","он","на","я","что","тот","быть","с","а","весь","это","как","она","по","но",
    "они","к","у","же","вы","за","бы","по","только","её","мне","было","вот","от","меня","ещё",
    "нет","о","из","ему","теперь","когда","даже","ну","вдруг","ли","если","уже","или","ни",
    "работать","код","данные","файл","игра","помощь","ввод","хранить","загружать","делать",
    "узел","открыть","запрос","читать","сохранять","тип","пользователь","вид","писать",
    "доступ","назад","диск","редактировать","найти","получить","держать","вставить",
    "присоединить","знать","ссылка","двигать","следующий","вывод","печать","запустить",
    "установить","время","обновить","проверить","ждать","создать","удалить","импорт",
    "экспорт","вернуть","функция","переменная","строка","число","логический","массив",
    "объект","класс","модуль","сервер","клиент","запрос","ответ","база","ошибка","отладка",
    "тест","развертывание","версия","ветка","коммит","слияние","толчок","тянуть","клон",
    "форк","проблема","выпуск","функция","баг","исправить","патч","обновление","установить",
    "удалить","настройка","параметр","значение","ключ","индекс","счётчик","длина","сортировка",
    "фильтр","карта","уменьшить","найти","включить","добавить","убрать","нарезать","разделить",
    "присоединить","разбить","обрезать","заменить","совпадение","поиск","начать","конец",
    "процесс","управление","доступ","загрузить","хранить","кэш","получить","отправить",
    "получить","подключить","отключить","открыть","закрыть","читать","писать","разбор",
    "формат","кодировать","декодировать","шифровать","расшифровать","хэш","подпись","токен",
    "сессия","куки","заголовок","тело","маршрут","путь","веб","приложение","мобильный",
    "облако","локальный","удалённый","хост","порт","поток","асинхронный","обещание","событие",
    "слушать","подписка","публикация","войти","выйти","регистрация","авторизация","роль",
    "администратор","имя","почта","пароль","профиль","настройка","уведомление","сообщение",
    "подтверждение","отмена","страница","список","таблица","форма","кнопка","ссылка","текст",
    "заголовок","раздел","контейнер","шаблон","компонент","плагин","библиотека","пакет",
    "зависимость","сборка","компиляция","запустить","тест","публикация","документация"
  ]
};

const DEV_WORDS = [
  "function","const","let","var","if","else","for","while","return","map","filter","reduce",
  "useState","useEffect","useRef","useMemo","useCallback","useContext","useReducer",
  "props","state","component","render","class","extends","constructor","super","static",
  "async","await","promise","then","catch","try","throw","new","this","typeof","instanceof",
  "null","undefined","true","false","NaN","Infinity","Array","Object","String","Number",
  "Boolean","Symbol","BigInt","console","log","error","warn","info","setTimeout","setInterval",
  "clearTimeout","clearInterval","fetch","json","parse","stringify","localStorage","sessionStorage",
  "addEventListener","removeEventListener","querySelector","querySelectorAll","getElementById",
  "createElement","appendChild","removeChild","innerHTML","textContent","style","classList",
  "getAttribute","setAttribute","dataset","href","src","alt","title","type","value","checked",
  "disabled","readonly","required","placeholder","autocomplete","spellcheck","contenteditable",
  "addEventListener","dispatchEvent","CustomEvent","MutationObserver","IntersectionObserver",
  "ResizeObserver","requestAnimationFrame","cancelAnimationFrame","performance","Date","Math",
  "floor","ceil","round","random","abs","max","min","pow","sqrt","PI","E","parseInt","parseFloat",
  "isNaN","isFinite","encodeURIComponent","decodeURIComponent","JSON","RegExp","Error","TypeError",
  "RangeError","SyntaxError","Promise","resolve","reject","all","race","any","allSettled",
  "generator","iterator","yield","Symbol","WeakMap","WeakSet","Map","Set","Proxy","Reflect",
  "Object","keys","values","entries","assign","freeze","seal","create","prototype","hasOwnProperty",
  "spread","rest","destructuring","arrow","template","tagged","nullish","optional","logical",
  "import","export","default","namespace","module","require","node","npm","yarn","pnpm","package",
  "webpack","vite","rollup","esbuild","babel","typescript","eslint","prettier","jest","vitest",
  "react","vue","angular","svelte","nextjs","nuxt","remix","astro","gatsby","express","fastify",
  "koa","nestjs","graphql","rest","http","https","websocket","grpc","protobuf","json","xml",
  "html","css","scss","sass","less","tailwind","styled","emotion","chakra","material","antd",
  "docker","kubernetes","nginx","apache","redis","postgres","mysql","mongodb","sqlite","prisma",
  "sequelize","mongoose","typeorm","drizzle","supabase","firebase","aws","gcp","azure","vercel",
  "netlify","heroku","railway","fly","cloudflare","github","gitlab","bitbucket","ci","cd",
  "git","init","add","commit","push","pull","merge","rebase","stash","cherry","pick","clone",
  "branch","checkout","switch","status","diff","log","reflog","bisect","blame","tag","release",
  "algorithm","complexity","bigO","linear","logarithmic","polynomial","exponential","recursive",
  "iterative","memoization","dynamic","greedy","backtracking","graph","tree","binary","heap",
  "queue","stack","linked","hash","trie","segment","fenwick","disjoint","sort","search","binary",
  "depth","breadth","dijkstra","bellman","floyd","kruskal","prim","topological","strongly",
  "connected","bipartite","matching","flow","network","string","pattern","kmp","rabin","suffix"
];

const QUOTES = {
  en: [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you are halfway there. - Theodore Roosevelt",
    "Your time is limited, do not waste it living someone else life. - Steve Jobs",
    "Stay hungry, stay foolish. - Steve Jobs",
    "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
    "Hard work beats talent when talent does not work hard. - Tim Notke",
    "The best time to plant a tree was twenty years ago. The second best time is now.",
    "Life is what happens to you while you are busy making other plans. - John Lennon",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Do not let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Do not let it stop you. - Unknown",
    "It is not whether you get knocked down, it is whether you get up. - Vince Lombardi",
    "If you are working on something that you really care about, you do not have to be pushed. - Steve Jobs",
    "Experience is a hard teacher because she gives the test first, the lesson afterwards.",
    "To know what you know and what you do not know, that is true knowledge. - Confucius",
    "The secret of getting ahead is getting started. - Mark Twain"
  ],
  uz: [
    "Bilim eng katta boylikdir, uni hech kim sendan tortib ololmaydi.",
    "Har bir katta maqsad kichik qadamdan boshlanadi.",
    "Muvaffaqiyatsizlik bu muvaffaqiyatga olib boruvchi yoldagi bir bekat.",
    "Kelajak oz orzulariga ishonganlarga tegishlidir.",
    "Har bir kun yangi imkoniyatlar eshigini ochadi.",
    "Oqish va organish hech qachon kech emas.",
    "Dunyoni ozgartirish uchun avval ozingni ozgartir.",
    "Vaqt eng qimmatli boylikdir, uni bekorga sarflamang.",
    "Dostlik va birodarlik eng ulug qadriyatlardandir.",
    "Mehnatsevarlik har qanday muvaffaqiyatning asosidir."
  ],
  ru: [
    "Znanie - sila. Kto vladeet informaciej, tot vladeet mirom.",
    "Uchitsya nikogda ne pozdno. Vsegda est vozmozhnost stat luchshe.",
    "Terpenie i trud vse peretrut. Nastojchivost pobezhdaet prepyatstviya.",
    "Vek zhivi - vek uchis. Znanie - eto svet, nezhelaniye - tma.",
    "Sem raz otmer, odin raz otrezh. Obyazatelno dumaj pered tem kak dejstvovat.",
    "Bez truda ne vytashish i rybku iz pruda. Uspeh trebuet usilij.",
    "Chto poseesh to i pozhnyosh. Tvoi dejstviya opredelyayut tvoe buduschee.",
    "Delu vremya potehe chas. Balans mezhdu rabotoj i otdyhom - klyuch k uspehu.",
    "Slovo ne vorobej vyletit ne pojmaesh. Govori obdumanno i otvetstvenno.",
    "Druzya poznayutsya v bede. Istinnye druzya vsegda ryadom kogda tyazhelo."
  ]
};

const SOUNDS = {
  // Mavjud ovozlar
  blue: { correct: 523.25, error: 261.63, type: 'sine', dur: 0.15 },
  brown: { correct: 440.00, error: 220.00, type: 'triangle', dur: 0.12 },
  red: { correct: 659.25, error: 329.63, type: 'square', dur: 0.1 },
  creamy: { correct: 493.88, error: 246.94, type: 'sine', dur: 0.18 },
  thock: { correct: 392.00, error: 196.00, type: 'sawtooth', dur: 0.2 },
  
  // YANGI OVOZLAR
  cherry: { correct: 783.99, error: 391.99, type: 'sine', dur: 0.08 },
  silent: { correct: 261.63, error: 130.81, type: 'sine', dur: 0.05 },
  typewriter: { correct: 880.00, error: 440.00, type: 'triangle', dur: 0.03 },
  mechanical: { correct: 659.25, error: 329.63, type: 'square', dur: 0.12 },
  retro: { correct: 523.25, error: 261.63, type: 'sawtooth', dur: 0.2 },
  bell: { correct: 1046.50, error: 523.25, type: 'sine', dur: 0.25 },
  click: { correct: 1000.00, error: 500.00, type: 'triangle', dur: 0.02 },
  deep: { correct: 261.63, error: 130.81, type: 'sawtooth', dur: 0.3 },
  light: { correct: 1318.52, error: 659.25, type: 'sine', dur: 0.1 },
  bass: { correct: 196.00, error: 98.00, type: 'sawtooth', dur: 0.35 }
};
const RANKS = [
  { name: "Noob",         min: 0,   stars: 1, next: 40 },
  { name: "O'rganuvchi",  min: 40,  stars: 2, next: 80 },
  { name: "Mohir",        min: 80,  stars: 3, next: 120 },
  { name: "Ustoz",        min: 120, stars: 4, next: 140 },
  { name: "Legend",       min: 140, stars: 5, next: null }
];
